CREATE TABLE [User].[Lang] (
    [UserID] INT     NOT NULL,
    [LangID] TINYINT NOT NULL,
    [Main]   BIT     CONSTRAINT [DF_Lang_Mian] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_Lang_2] PRIMARY KEY CLUSTERED ([UserID] ASC, [LangID] ASC),
    CONSTRAINT [FK_Lang_Account] FOREIGN KEY ([UserID]) REFERENCES [User].[Account] ([UserID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_Lang_LangList] FOREIGN KEY ([LangID]) REFERENCES [Lang].[LangList] ([LangID]) ON DELETE CASCADE ON UPDATE CASCADE
);

